import { useState } from 'react'
import './index.css'

const nav = [['Overview', '[]'], ['Inbox', '()'], ['Leads', '++'], ['Automations', '~>'], ['Analytics', '/\\']]
const leads: [string, string, string, string, number, string, string][] = [['AM', 'Aarav Mehta', 'Finverse', 'Qualified', 92, '$18,500', 'purple'], ['SN', 'Sofia Nguyen', 'Northstar Labs', 'Qualifying', 86, '$12,000', 'green'], ['EB', 'Elliot Brooks', 'Vantage Co.', 'Handoff', 81, '$24,000', 'orange'], ['MP', 'Maya Patel', 'Flowgrid', 'New', 78, '$9,800', 'pink']]
const chats = [['AM', 'Aarav Mehta', '2m', 'Does your team support HubSpot routing rules?', 'purple'], ['SN', 'Sofia Nguyen', '14m', 'We are comparing plans for a 24-seat team.', 'green'], ['EB', 'Elliot Brooks', '32m', 'Booked. Looking forward to the product walk-through.', 'orange']]

function App() {
  const [active, setActive] = useState('Overview')
  const [period, setPeriod] = useState('Weekly')
  const [modal, setModal] = useState<'lead' | 'search' | null>(null)
  const [notice, setNotice] = useState('')
  const toast = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2300) }
  return <div className="app">
    <aside className="side">
      <div className="brand"><span>K</span> KINETIC</div>
      <button className="workspace" onClick={() => toast('Workspace switcher opened')}><i>N</i><b>Northstar<small>Sales workspace</small></b><em>v</em></button>
      <nav><p>WORKSPACE</p>{nav.map(([label, icon]) => <button key={label} className={active === label ? 'selected' : ''} onClick={() => setActive(label)}><span>{icon}</span>{label}{label === 'Inbox' && <mark>12</mark>}</button>)}</nav>
      <div className="side-bottom"><div className="usage"><div><span>AI conversations</span><b>68%</b></div><i><i /></i><small>1,362 of 2,000 this month</small><button onClick={() => toast('Plan options opened')}>Upgrade plan <b>-&gt;</b></button></div><button className="profile" onClick={() => toast('Account menu opened')}><i>MS</i><b>Maya Shah<small>Admin</small></b><em>...</em></button></div>
    </aside>
    <main>
      <header><div><p>MONDAY, OCTOBER 14</p><h1>{active === 'Overview' ? 'Good morning, Maya' : active}</h1></div><div className="header-actions"><button className="search" onClick={() => setModal('search')}><span>Search</span><kbd>Ctrl K</kbd></button><button className="bell" aria-label="Notifications" onClick={() => toast('You have 3 new notifications')}>!<i /></button><button className="primary" onClick={() => setModal('lead')}><b>+</b> New lead</button></div></header>
      {active !== 'Overview' ? <section className="placeholder"><i>{nav.find((item) => item[0] === active)?.[1]}</i><h2>{active}</h2><p>This workspace is ready for the next Kinetic module.</p><button className="primary" onClick={() => setActive('Overview')}>Return to overview</button></section> : <>
        <section className="signal"><i>*</i><p><b>Kinetic AI is performing well.</b> It qualified 8 leads while you were away.</p><button onClick={() => setActive('Inbox')}>View conversations -&gt;</button></section>
        <section className="metrics"><Metric icon="()" color="purple" title="Active conversations" value="128" delta="12.4%" /><Metric icon="++" color="green" title="Qualified leads" value="36" delta="18.2%" /><Metric icon="$" color="orange" title="Pipeline value" value="$248.6k" delta="8.6%" /><Metric icon="%" color="pink" title="AI resolution rate" value="74.8%" delta="4.1%" /></section>
        <section className="grid">
          <article className="card pipeline"><CardTitle title="Pipeline health" sub="Qualified opportunities by stage" action={<div className="tabs">{['Weekly', 'Monthly'].map((value) => <button onClick={() => setPeriod(value)} className={period === value ? 'on' : ''} key={value}>{value}</button>)}</div>} /><div className="pipeline-total"><b>{period === 'Weekly' ? '$248,600' : '$782,300'}</b><span>Current pipeline value</span><em>+8.6%</em></div><div className="chart"><div className="axis"><span>$80k</span><span>$60k</span><span>$40k</span><span>$20k</span><span>$0</span></div><div className="graph"><div className="lines" /><svg viewBox="0 0 700 180" preserveAspectRatio="none"><defs><linearGradient id="fade" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#7c5cff" stopOpacity=".25" /><stop offset="1" stopColor="#7c5cff" stopOpacity="0" /></linearGradient></defs><path d="M0 145C45 135 64 108 106 120S165 93 214 104S274 72 323 85S380 54 432 72S492 48 541 44S594 18 700 27V180H0Z" fill="url(#fade)" /><path d="M0 145C45 135 64 108 106 120S165 93 214 104S274 72 323 85S380 54 432 72S492 48 541 44S594 18 700 27" fill="none" stroke="#7c5cff" strokeWidth="3" vectorEffect="non-scaling-stroke" /><circle cx="541" cy="44" r="5" fill="white" stroke="#7c5cff" strokeWidth="3" vectorEffect="non-scaling-stroke" /></svg><div className="chart-labels"><span>Oct 7</span><span>Oct 8</span><span>Oct 9</span><span>Oct 10</span><span>Oct 11</span><span>Oct 12</span><span>Today</span></div></div></div><div className="legend"><Legend color="purple" label="Discovery" value="$74.2k" /><Legend color="blue" label="Qualification" value="$96.8k" /><Legend color="green" label="Proposal" value="$48.6k" /><Legend color="orange" label="Handoff" value="$29.0k" /></div></article>
          <article className="card inbox"><CardTitle title="AI inbox" sub="Recent conversations that need attention" action={<button className="link" onClick={() => setActive('Inbox')}>Open inbox -&gt;</button>} /><div className="chat-list">{chats.map(([initials, name, time, text, color], index) => <button key={name} className="chat" onClick={() => toast('Opened conversation with ' + name)}><i className={color}>{initials}</i><span><b>{name}<time>{time}</time></b><small>{text}</small></span>{index < 2 && <em />}</button>)}</div><button className="view-all" onClick={() => setActive('Inbox')}>View all conversations -&gt;</button></article>
          <article className="card lead-card"><CardTitle title="Priority leads" sub="Highest intent signals from AI" action={<button className="link" onClick={() => setActive('Leads')}>View all -&gt;</button>} /><div className="table"><div className="table-head"><span>Lead</span><span>Stage</span><span>Score</span><span>Deal</span><span /></div>{leads.map(([initials, name, company, stage, score, deal, color]) => <div className="lead" key={name}><div><i className={color}>{initials}</i><span><b>{name}</b><small>{company}</small></span></div><span><em className={'stage ' + stage.toLowerCase()}>{stage}</em></span><span className="score"><b>{score}</b><i><i style={{ width: score + '%' }} /></i></span><b>{deal}</b><button aria-label={'Open ' + name} onClick={() => toast('Opened ' + name + ' lead profile')}>-&gt;</button></div>)}</div></article>
          <article className="card activity"><CardTitle title="Live activity" sub="What Kinetic is working on now" action={<span className="live"><i />Live</span>} /><Activity time="Now" icon="AI" color="purple" text={<><b>AI is qualifying</b> a new lead from <strong>Acme Studio</strong></>} /><Activity time="2m" icon="++" color="green" text={<><b>Sofia Nguyen</b> moved to qualification</>} /><Activity time="8m" icon="-&gt;" color="orange" text={<><b>Demo booked</b> with Elliot Brooks for tomorrow</>} /><Activity time="16m" icon="!" color="pink" text={<><b>Follow-up sent</b> to 4 warm leads</>} /></article>
        </section>
      </>}
    </main>
    {modal === 'lead' && <div className="overlay" onMouseDown={() => setModal(null)}><form className="modal" onMouseDown={(event) => event.stopPropagation()} onSubmit={(event) => { event.preventDefault(); setModal(null); toast('New lead created') }}><div><p>PIPELINE</p><h2>Add a new lead</h2></div><button type="button" className="close" onClick={() => setModal(null)}>x</button><label>Full name<input required placeholder="e.g. Jordan Lee" /></label><label>Company<input required placeholder="e.g. Acme Studio" /></label><label>Estimated deal value<input required placeholder="$0" /></label><footer><button type="button" onClick={() => setModal(null)}>Cancel</button><button className="primary">Create lead</button></footer></form></div>}
    {modal === 'search' && <div className="overlay search-overlay" onMouseDown={() => setModal(null)}><div className="search-modal" onMouseDown={(event) => event.stopPropagation()}><i>/</i><input autoFocus placeholder="Search leads, conversations, companies..." /><kbd>Esc</kbd></div></div>}
    {notice && <div className="toast">{notice}</div>}
  </div>
}
function Metric({ icon, color, title, value, delta }: { icon: string; color: string; title: string; value: string; delta: string }) { return <article className="metric"><i className={color}>{icon}</i><p>{title}</p><div><b>{value}</b><span>+{delta}</span></div><small>vs. last week</small></article> }
function CardTitle({ title, sub, action }: { title: string; sub: string; action: React.ReactNode }) { return <div className="card-title"><div><h2>{title}</h2><p>{sub}</p></div>{action}</div> }
function Legend({ color, label, value }: { color: string; label: string; value: string }) { return <div><i className={color} /><span>{label}</span><b>{value}</b></div> }
function Activity({ time, icon, color, text }: { time: string; icon: string; color: string; text: React.ReactNode }) { return <div className="activity-row"><time>{time}</time><i className={color}>{icon}</i><p>{text}</p></div> }
export default App
